id: template_chat_flow
name: Template Chat Flow
inputs:
  chat_history:
    type: list
    is_chat_input: false
    is_chat_history: true
  question:
    type: string
    is_chat_input: true
outputs:
  answer:
    type: string
    reference: ${final.output}
    is_chat_output: true
  merge_state:
    type: string
    reference: ${merge_state.output}
nodes:
- name: spell_check
  type: llm
  source:
    type: code
    path: prompts/spell_check.jinja2
  inputs:
    deployment_name: gpt-4o-mini-gs-2024-07-18
    temperature: 0
    top_p: 1
    question: ${inputs.question}
  provider: AzureOpenAI
  connection: pf-openai-use2-id-auth
  api: chat
  module: promptflow.tools.aoai
  use_variants: false
- name: extraction
  type: python
  source:
    type: code
    path: nodes/extraction.py
  inputs:
    user_input: ${spell_check.output}
  use_variants: false
- name: load_state
  type: python
  source:
    type: code
    path: nodes/load_state.py
  inputs:
    chat_history: ${inputs.chat_history}
  use_variants: false
- name: merge_state
  type: python
  source:
    type: code
    path: nodes/merge_state.py
  inputs:
    new_extraction: ${extraction.output}
    prev_state: ${load_state.output}
  use_variants: false
- name: validation
  type: python
  source:
    type: code
    path: nodes/validation.py
  inputs:
    updated_json: ${merge_state.output}
  use_variants: false
- name: ask_or_finalize
  type: llm
  source:
    type: code
    path: prompts/ask_or_finalize.jinja2
  inputs:
    deployment_name: gpt-4o-gs-2024-05-13
    temperature: 0
    top_p: 1
    complete: ${validation.output.complete}
    missing: ${validation.output.missing}
    state: ${validation.output.state}
  provider: AzureOpenAI
  connection: pf-openai-use2-id-auth
  api: chat
  module: promptflow.tools.aoai
  use_variants: false
- name: router
  type: python
  source:
    type: code
    path: nodes/router.py
  inputs:
    prev: ${ask_or_finalize.output}
  use_variants: false
- name: wps_json_builder
  type: python
  source:
    type: code
    path: nodes/wps_json_builder.py
  inputs:
    as_dict: ${router.output.as_dict}
    as_string: ${router.output.as_string}
  use_variants: false
- name: wps_api
  type: python
  source:
    type: code
    path: nodes/wps_api.py
  inputs:
    api_key: y88XqCYtjLD2SvfGrnO3rnToqxxiuOg2Cth1vXeACIAzSeBZGtHS
    api_version: 2023-11-01
    body: ${wps_json_builder.output}
    endpoint: https://pf-t332-cog-srch-test-euw1-cvx.search.windows.net
    index_name: wps-diain
  use_variants: false
- name: pwht_check
  type: python
  source:
    type: code
    path: nodes/pwht_check.py
  inputs:
    line_class: ${validation.output.state.line_class}
    search_result: ${wps_api.output}
  use_variants: false
- name: nde
  type: python
  source:
    type: package
    tool: promptflow_vectordb.tool.common_index_lookup.search
  inputs:
    mlindex_content: >
      embeddings:
        api_base: https://pf-t332-openai-use2.openai.azure.com/
        api_type: azure
        api_version: '2024-10-21'
        batch_size: '1'
        connection:
          id: /subscriptions/baa67dbf-45d0-4d84-b662-527186361068/resourceGroups/pf-T332-t-dsws/providers/Microsoft.MachineLearningServices/workspaces/pf-T332-dsws-test-euw1-tc-cvx/connections/pf-openai-use2-id-auth
        connection_type: workspace_connection
        deployment: text-embedding-ada-002-gs-2
        dimension: 1536
        kind: open_ai
        model: text-embedding-ada-002
        schema_version: '2'
      index:
        api_version: '2023-11-01'
        connection:
          id: /subscriptions/baa67dbf-45d0-4d84-b662-527186361068/resourceGroups/pf-T332-t-dsws/providers/Microsoft.MachineLearningServices/workspaces/pf-T332-dsws-test-euw1-tc-cvx/connections/pf-t332-t-cog
        connection_type: workspace_connection
        endpoint: https://pf-t332-cog-srch-test-euw1-cvx.search.windows.net/
        engine: azure-sdk
        field_mapping:
          content: content
          embedding: null
          metadata: pmi_percent
        index: ndeee
        kind: acs
        semantic_configuration_name: ndeee-semantic-configuration
    queries: ${validation.output.state.line_class}
    query_type: Keyword
    top_k: 1
  activate:
    when: ${validation.output.complete}
    is: true
  use_variants: false
- name: nde_py
  type: python
  source:
    type: code
    path: nodes/nde_py.py
  inputs:
    input1: ${nde.output}
    line_class: ${validation.output.state.line_class}
  activate:
    when: ${validation.output.complete}
    is: true
  use_variants: false
- name: material
  type: python
  source:
    type: code
    path: nodes/material.py
  inputs:
    search_output: ${nde.output}
  use_variants: false
- name: template
  type: python
  source:
    type: code
    path: nodes/template.py
  inputs:
    facts: ${ask_or_finalize.output}
    material: ${material.output}
    nde_result: ${nde_py.output}
    wps_result: ${pwht_check.output}
  use_variants: false
- name: final
  type: llm
  source:
    type: code
    path: prompts/final.jinja2
  inputs:
    deployment_name: gpt-4o-gs-2024-05-13
    temperature: 0
    top_p: 1
    question: ${template.output}
  provider: AzureOpenAI
  connection: pf-openai-use2-id-auth
  api: chat
  module: promptflow.tools.aoai
  use_variants: false
node_variants: {}
environment:
  python_requirements_txt: requirements.txt
